config/routes.rb
Rails.application.routes.draw do
    
    resources :students do 
        resources :results
    end
    
    resources :results
    resources :students
    resources :users
    resources :pfilters
    resources :lfilters
    resources :parents

    post '/search' => 'students#search'

    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'


  
    resources :sessions, only: [:new, :create, :destroy]
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#create', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'page/index'
    
    # You can have the root of your site routed with "root"
    #ROOT PAGE IS THE STATI_COTROLLER'S INDEX METHOD WHICH WILL BE RENDERED IN VIEWS
    root 'static_pages#home'
    get '/about' => 'static_pages#about'
    get '/policy' => 'static_pages#policy'
    get '/contact' => 'static_pages#contact'
    get '/demotivators' => 'static_pages#demotivators'
    get '/real_fun' => 'static_pages#real_fun'
 

	match ':controller(/:action(/:id))', :via => :get


end

app/models/student.rb
class Student < ActiveRecord::Base
 #in orer to have proper connection
  def student_params
      params.require(:student).permit(:name, :surname, :day_of_birth, :month_of_birth, :year_of_birth, :school, :email, :comment)
   
  end
#has_many :results, :dependent => :delete_all
 #has_many :results, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
#include is inheritence to get the contents of the helper. 
#This is to avoid writing repetative code and is therefore achieveing DRYness
include UsersHelper

  before_action :set_student, only: [:show, :edit, :update, :destroy], except: [:parent_filter]
  
  
  #extra security the username for teacher will have a name+surname
  #does not work ath the moment fix later
  #def current_user
   # User.where(id: session[:user_id]).first
  #end
   #@user = current_user

  #promt protecting pages in this controller (but save later to maek secure)
  #do not use on public computers the passwor is rememberd
 
   #extra security - the password for the teachers will be current date + a password  = each day different
   @date = Time.now.strftime("%e")
   #name can be anythig else like email, surname, username or wahtever
   #password can be anything as well like the school to which the autharisation is made
   #password and user params can be connected to the database and a SchoolApp admin could 
   #update it once request is made by the school to access the teacher dashboard
   #dynamic password will change every day 
   http_basic_authenticate_with :name => "@user", :password => @date + "12345"
  

  def search
    @search_term = params[:q]
    #@the search term is what will be presented in q
    st ="%#{params[:q]}%"
    #seatchterm will be used to search in students table searchin for the first name here
    @students = Student.where("lower(email) like (?) or lower(surname) like (?) or lower(school) like (?)", st.downcase, st.downcase, st.downcase)
  end
  
  def pfilter
    #add if the current user email matches the pfilter email the show (maybe in views)
      #st = params[:pfilter] (this does not work with emails for some reason)
      st ="%#{params[:pfilter]}%"
      #now compare that filter name with student
      @students= Student.where("school like (?) or surname like (?) or email like (?)",st,st, st) #
      #display all the pfilters
      #@pfilters = Pfilter.all
      #displaying currnet user
      #@user = current_user.email
      #display the pfilters with the current user
      #@pfilters= Pfilter.where("email like ? ", @user) 
     # @students= Student.where("school like ? ", st)
  
  end
  def parent_filter
      @pfilters = Pfilter.all
      
     #add if the current user email matches the pfilter email the show (maybe in views)
      st = params[:pfilter]
      #now compare that filter name with student
      @students= Student.where("school like (?) or surname like (?) or email like (?)",st,st, st) 
  
  end


  # GET /students
  # GET /students.json
  def index
  
    #calling all the addon functions
    #@pfilters = Pfilter.all
    @students = Student.all

    ##Here we personalise filters so that each user will have their own unique filte
    #displaying currnet user
    st=@user_email
    #display the pfilters with the current user
    @pfilters= Pfilter.where("email like ? ", st) 

  end

  # GET /students/1
  # GET /students/1.json
  def show
    #need to get the currnet user in order to display in the header
  ###  @user = current_user
      
    #getting a firstname and surname to prefill in the _form
  ###  @user_first_name= current_user.first_name
  ###  @user_last_name= current_user.last_name
      
  end

  # GET /students/new
  def new
    #need to get the currnet user in order to display in the header
    @user = current_user
  
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    #need to get the currnet user in order to display in the header
  ###  @user = current_user
      
    #getting a firstname and surname to prefill in the _form
  ###  @user_first_name= current_user.first_name
  ###  @user_last_name= current_user.last_name
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_url, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json#
  def destroy
    #@student= Student.find(params[:id])
    Result.where("email like ? ", @student.email ).delete_all
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :day_of_birth, :month_of_birth, :year_of_birth, :school, :email, :comment)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<%#deleting all the rest of the code because it is not needed %>
<%= render 'form' %>

app/views/students/filter.html.erb
    <h1>Categories Filter</h1>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Categories Filter</title>
        <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    </head>

    <body>


        <% if @students.length == 0 %>
        <!--empty filter error-->
        <div id="empty" >
            <h2>We are sorry, 
                <br><br>
                there are no students
                <br><br>
            in this filter</h2>  
        </div>
        <% end %>

        <div class="table-title">
            <h3>Students Table</h3>
        </div>
        <table class="table-fill">
           
            <thead>
                <tr>
                   <%= link_to 'New Student', new_student_path %>
                   <th class="text-left">Name</th>
                   <th class="text-left">Date of Birth</th>
                   <th class="text-left">School</th>
                   <th class="text-left">Email</th>
                   <th class="text-left">Comment</th>
                   <th class="text-left">Edit/Destroy/Add</th>
               </tr>
           </thead>
           <tbody class="table-hover">
            <% @students.each do |student| %>
            <tr>                                      
                <td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
                <td class="text-left"><%= "#{student.day_of_birth} /" %>  
                    <%= "#{student.month_of_birth} /"%>
                    <%= student.year_of_birth %></td>
                    <td class="text-left"> <%= student.school %></td>
                    <td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'index', :id =>  student.email}) %>
                    </td>
                    <td class="text-left"> <%= student.comment %></td>
                    <td class="text-left"> <% if user_signed_in? %>
                      <%= link_to 'Edit', edit_student_path(student) %>
                      <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <%else%>
                      <%end%> </td>
                      
                      
                  </tr>
                  <tr>

                  </tr>

              </tbody>

              <% end %>
          </table>
          

      </body>
      <h1>Categories Filter</h1>
      <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>Categories Filter</title>
        <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
    </head>

    <body>


        <% if @students.length == 0 %>
<!--empty filter error--->
  <div id="empty" >
    <h2>We are sorry, 
    <br><br>
    there are no students
    <br><br>
    in this filter</h2>  
  </div>
<% end %>

<div class="table-title">
<h3>Students Table</h3>
</div>
<table class="table-fill">
 
<thead>
<tr>
     <%= link_to 'New Student', new_student_path %>
<th class="text-left">Name</th>
<th class="text-left">Date of Birth</th>
<th class="text-left">School</th>
<th class="text-left">Email</th>
<th class="text-left">Comment</th>
<th class="text-left">Edit/Destroy/Add</th>
</tr>
</thead>
<tbody class="table-hover">
    <% @students.each do |student| %>
<tr>                                      
<td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
<td class="text-left"><%= "#{student.day_of_birth} /" %>  
            <%= "#{student.month_of_birth} /"%>
            <%= student.year_of_birth %></td>
<td class="text-left"> <%= student.school %></td>
<td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'index', :id =>  student.email}) %>
</td>
<td class="text-left"> <%= student.comment %></td>
<td class="text-left"> <% if user_signed_in? %>
              <%= link_to 'Edit', edit_student_path(student) %>
              <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
               <%else%>
            <%end%> </td>
            
           
</tr>
<tr>

</tr>

</tbody>

 <% end %>
</table>
  

  </body>

app/views/students/index.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    
    <!-- the same applies to the rest of the code. The elemets that I've already declare that are comming form the template are similar below-->
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title><%= yield(:title) %>Teacher's Dashboard</title>


    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

 
    <!-- Bootstrap core CSS the --> <!--the line below is taken from a template
    <link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">-->
    <% stylesheet_link_tag "bootstrap.min"%>
    <!-- Animation library for notifications   --><!--the line below is taken from a template
    <link href="assets/stylesheets/animate.min.css" rel="stylesheet">-->
    <% stylesheet_link_tag "animate.min"%>
    <!--  Light Bootstrap Table core CSS    --><!--the line below is taken from a template
    <link href="assets/stylesheets/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet">-->
    <% stylesheet_link_tag "light-bootstrap-dashboard"%>


 <!--     Fonts and icons     --><!--the line below is taken from a template-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!--the line below is taken from a template-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">
    <!--the line below is taken from a template
    <link href="assets/stylesheets/pe-icon-7-stroke.css" rel="stylesheet">-->
   <% stylesheet_link_tag "pe-icon-7-stroke"%>
    

    
    
    <link href="https://ajax.googleapis.com/ajax/libs/jquery/3.0.1/jquery.min.jsy">
</head>
<body>
   <%= render 'layouts/header' %>
   

<div class="content purple-horizontal">
   <p id="notice"><%= notice %></p>
   <div class="container-fluid">
    <div class="row">
        
        <div class="col-md-12">
            <div class="card card-plain">
                <div class="header">
                    <h4 class="title">ALL Students By Filters Table</h4>
                    <p class="category">This table contains all students whose surname(s) or email(s) are in the filter table</p>
                    <p style="margin-bottom:1.5%;"><%= render 'layouts/search' %></p><br>
                    <p class="category"><%= link_to ' ADD a New Student', new_student_path, class: "btn purple-button" %></p>
                    <br>
                    
                </div>
           <div class="content table-responsive table-full-width">
                        <table class="table table-hover table-striped">
                        <thead>
                            <th class="text-left">Name</th>
                            <th class="text-center">Date of Birth</th>
                            <th class="text-center">School</th>
                            <th class="text-center">Email</th>
                            <th class="text-center">Results</th>
                            <th class="text-center">Comment</th>
                            <th class="text-center">Edit/Delete</th>
                        </thead>
                        

                        
                        <!--ROW 1 -->
                        <!-- check if the code below works. if deleting the table all works so the prob is in the tble / the prob is that for sure the lfilters themselves is more than 0-->
                        <!--    -->
                        <% if @students.length == 0 || @pfilters.length == 0 %>
                        <div class="col-md-6">
                            <div class="card card-plain">
                                <div class="header">
                                    <h4 class="text-warning">There are no resutls for the student/s you are looking for by what you are filtering (the student or/and the filter does not exist yet). Add a filter first and if same message appears then add a student)</h4>
                                    
                                </div>
                            </div>
                        </div>
                        <% end %>

                        <tbody>
                            
                           <tr>
                               
                               <!--ADD IF NO PFILTERS to display no filters result-->
                               <!--IF ONE STUDENT IS THE RESULT OF THE FILTER THEN MAYBE GO STRAIGN TO MARKS?-->
                               
                               <% @pfilters.each do |pfilter| %>
                               <% @students.each do |student| %>
                               <% if pfilter.pfilter.casecmp(student.surname) == 0 || pfilter.pfilter.casecmp(student.email) == 0 ||  pfilter.pfilter.casecmp(student.school) == 0%>
                               <tr>
                                <td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
                                <td class="text-center"><%= "#{student.day_of_birth} /" %>  
                                    <%= "#{student.month_of_birth} /"%>
                                    <%= student.year_of_birth %></td>
                                    <td class="text-center"> <%= student.school %></td>
                                    <td class="text-center"> <%= student.email %></td>
                                    <td class="text-center"><%= link_to("Results", {:controller => 'results', :action => 'teacher_result', :id =>  student.email}) %>
                                    </td>
                                    <td class="text-center"> <%= student.comment %></td>
                                    <!--make the whole page not work if not signed in and delte this sing in-->
                                    <td  class="text-center"><% if current_user %>
                                      <%= link_to 'Edit', edit_student_path(student) %>/
                                      <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
                                      <%else%>
                                      <% end %>                                </td>

                                      <% end %>

                                      <% end %>


                                  </tbody>


                              </td>
                          </tr>
                          
                          <%end%>
                          
                          
                      </table>


                  </div>
              </div>
          </div>
          
          
          
          <!-- All Students TABLE BEGIN-->   


          
          
          <div class="col-md-12">
           
           <p>
               <button class="btn purple-button btn-primary" type="button" data-toggle="collapse" data-target="#collapse" aria-expanded="collapse">
                  Filter Table
              </button>
          </p>
          <div class="collapse" id="collapse">
              <div class="card card-body">
                  
                  
                <div class="card">
                    <div class="header">
                        <h4 class="title">Filter Table</h4>
                        <p class="category">This table contains filters - school,surname or email</p><br>
                        <p><%= link_to 'Add a Student Filter', new_pfilter_path, class: "btn purple-button" %> </p>
                        

                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-hover table-striped">
                            <thead>
                              <!--<th>School/Surname/Email</th>-->
                              <th>Filter Keywords</th>
                              <th class="text-left">Edit/Delete</th>
                          </thead>
                          
                          <!--ROW 1 -->
                          <!-- check if the code below works. if deleting the table all works so the prob is in the tble / the prob is that for sure the lfilters themselves is more than 0-->
                          <!-- check for 0 filters -->
                          <!-- !!!!!Some of th eheaders need to be rendered before the chekc so that the code does no repeat -->
                          <% if @pfilters.length == 0 %>
                          <div class="col-md-6">
                            <div class="card card-plain">
                                <div class="header">
                                    <h4 class="text-warning">There are no matches in this filter (add a filter first to see resutls if student exist in the database)</h4><br>
                                    
                                </div>
                            </div>
                        </div>
                        <% end %>
                        <tbody>
                            
                         <tr>   
                            <!--ADD IF NO PFILTERS to display no filters result-->
                            <!--IF ONE STUDENT IS THE RESULT OF THE FILTER THEN MAYBE GO STRAIGN TO MARKS?-->
                            <!-- this should nave ELSE here from if filters==0-->
                            
                            <% @pfilters.each do |pfilter| %>
                            <tr>
                                <td><%= pfilter.pfilter %></td>
                                <!--<td><%# pfilter.email %></td>-->
                                <td><% if current_user %>
                                    <%#link_to 'Show', pfilter %> 
                                    <%= link_to 'Edit', edit_pfilter_path(pfilter) %> /
                                    <%= link_to 'Delete', pfilter, method: :delete, data: { confirm: 'Are you sure?' } %>
                                    <%else%>
                                    <%end%>
                                </td>
                            </tr>
                            
                            
                            <% end %>
                            
                        </table>

                    </div>
                </div>
            </div>
            <!--  Filter TABLE END-->   


            
            
        </div>
    </div>
    <tbody class="table-hover">
        <tr>
        </tr>

    </tbody>    
    <!--  All Students TABLE END-->       
    


</div>
</div>
</div>




<%= render 'layouts/footer' %>


</div>
</div>



</body>



<%javascript_include_tag "jquery.3.2.1.min.js"%>
<!--the line below is taken from a template
<script src="assets/javascripts/bootstrap.min.js" type="text/javascript"></script>-->
<%javascript_include_tag "bootstrap.min.js"%>
<!--  Charts Plugin --> <!--the line below is taken from a template
<script src="assets/javascripts/chartist.min.js"></script>-->
<%javascript_include_tag "chartist.min.js"%>
<!--  Notifications Plugin    --> <!--the line below is taken from a template
<script src="assets/javascripts/bootstrap-notify.js"></script>-->
<%javascript_include_tag "bootstrap-notify.js"%>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose --> 
<!--the line below is taken from a template
<script src="assets/javascripts/light-bootstrap-dashboard.js?v=1.4.0"></script>-->
<%javascript_include_tag "light-bootstrap-dashboard.js"%>



</html>

app/views/students/new.html.erb
<%#deleting all the rest of the code because it is not needed %>
<%= render 'form' %>

app/views/students/parent_filter.html.erb
<h1>Personal Filter (views/students/parents_filter.html.erb)</h1>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Categories Filter</title>
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>



   <br/>

<% if @students.length == 0 %>
<!--empty filter error--->
  <div id="empty" >
    <h2>We are sorry, 
    <br><br>
    there are no students
    <br><br>
    in this filter</h2>  
  </div>
<% end %>

<div class="table-title">
<h3>Students Table</h3>
</div>
<table class="table-fill">
 
<thead>
<tr>
     <%= link_to 'New Student', new_student_path %>
<th class="text-left">Name</th>
<th class="text-left">Date of Birth</th>
<th class="text-left">School</th>
<th class="text-left">Email</th>
<th class="text-left">Comment</th>
<th class="text-left">Edit/Destroy/Add</th>
</tr>
</thead>
<tbody class="table-hover">
    <% @students.each do |student| %>
<tr>                                      
<td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
<td class="text-left"><%= "#{student.day_of_birth} /" %>  
            <%= "#{student.month_of_birth} /"%>
            <%= student.year_of_birth %></td>
<td class="text-left"> <%= student.school %></td>
<td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'index', :id =>  student.email}) %>
</td>
<td class="text-left"> <%= student.comment %></td>

            
           
</tr>
<tr>

</tr>

</tbody>

 <% end %>
</table>
  

  </body>

app/views/students/pfilter.html.erb
<h1>Personal Filter (views/students/pfilter.html.erb)</h1>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Categories Filter</title>
    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>


<br/>

<% if @students.length == 0 %>
<!--empty filter error-->
<div id="empty" >
    <h2>We are sorry, 
        <br><br>
        there are no students
        <br><br>
    in this filter</h2>  
</div>
<% end %>

<div class="table-title">
    <h3>Students Table</h3>
</div>
<table class="table-fill">
   
    <thead>
        <tr>
           <%= link_to 'New Student', new_student_path %>
           <th class="text-left">Name</th>
           <th class="text-left">Date of Birth</th>
           <th class="text-left">School</th>
           <th class="text-left">Email</th>
           <th class="text-left">Comment</th>
           <th class="text-left">Edit/Destroy/Add</th>
       </tr>
   </thead>
   <tbody class="table-hover">
    <% @students.each do |student| %>
    <tr>                                      
        <td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
        <td class="text-left"><%= "#{student.day_of_birth} /" %>  
            <%= "#{student.month_of_birth} /"%>
            <%= student.year_of_birth %></td>
            <td class="text-left"> <%= student.school %></td>
            <td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'index', :id =>  student.email}) %>
            </td>
            <td class="text-left"> <%= student.comment %></td>
            <td class="text-left"> <% if user_signed_in? %>
              <%= link_to 'Edit', edit_student_path(student) %>
              <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
              <%else%>
              <%end%> </td>
              
              
          </tr>
          <tr>

          </tr>

      </tbody>

      <% end %>
  </table>
  

</body>

app/views/students/search.html.erb
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Search Results</title>
    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>


<%= render 'layouts/header' %>

<div class="content purple-horizontal">
    <div class="col-md-12">
       
        <div class="header">
            <div class="container-fluid">
                
                <h2>You searched for "<%= @search_term %>" </h2>
                
                <% if @students.length ==0 %>
                <div class="header">
                    <h4 class="title">No students are with that parameter in the Database.</h4>
                    <h4 class="title">Make sure your spelling is correct and if so then that </h4>
                    <h4 class="title">means that there are no students created yet with this parameter.</h4>

                    <br>
                </div>
            </div>
        </div>
        <% else %>



        



        <div class="header">
            
           
            <h4 class="title">Found Students</h4>
            
        </div>
        
        <div class="content">
            <table class="table table-hover">
                <thead>
                    <th class="text-left">Name</th>
                    <th class="text-center">Date of Birth</th>
                    <th class="text-center">School</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Results</th>
                    <th class="text-center">Comment</th>
                    <th class="text-center">Edit/Delete</th>
                </thead>
                

                
                <!--ROW 1 -->
                <!-- check if the code below works. if deleting the table all works so the prob is in the tble / the prob is that for sure the lfilters themselves is more than 0-->
                <!--    -->

                <tbody>
                    
                   <tr>
                       <!--ADD IF NO PFILTERS to display no filters result-->
                       <!--IF ONE STUDENT IS THE RESULT OF THE FILTER THEN MAYBE GO STRAIGN TO MARKS?-->
                       
                       
                       <% @students.each do |student| %>

                       <tr>
                        <td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
                        <td class="text-center"><%= "#{student.day_of_birth} /" %>  
                            <%= "#{student.month_of_birth} /"%>
                            <%= student.year_of_birth %></td>
                            <td class="text-center"> <%= student.school %></td>
                            <td class="text-center"> <%= student.email %></td>
                            <td class="text-center"><%= link_to("Results", {:controller => 'results', :action => 'teacher_result', :id =>  student.email}) %>
                            </td>
                            <td class="text-center"> <%= student.comment %></td>
                            <!--make the whole page not work if not signed in and delte this sing in-->
                            <td  class="text-center"><% if current_user %>
                              <%= link_to 'Edit', edit_student_path(student) %>/
                              <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
                          </td>

                          <% end %>
                          <% end %>



                      </tbody>


                  </td>
              </tr>
              
              <%end%>
              
              
          </table>
          
          <br>
          <p class="category"><%= link_to ' ADD a New Student', new_student_path, class: "btn purple-button" %></p>
          <%= link_to 'Back', students_path %>


      </div>
  </div>
</div>
</div>
</div>
<%= render 'layouts/footer' %>