config/routes.rb
Rails.application.routes.draw do
    
    resources :students do 
        resources :results
    end
    
    resources :results
    resources :students
    resources :users
    resources :pfilters
    resources :lfilters
    resources :parents

    post '/search' => 'students#search'

    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'


  
    resources :sessions, only: [:new, :create, :destroy]
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#create', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'page/index'
    
    # You can have the root of your site routed with "root"
    #ROOT PAGE IS THE STATI_COTROLLER'S INDEX METHOD WHICH WILL BE RENDERED IN VIEWS
    root 'static_pages#home'
    get '/about' => 'static_pages#about'
    get '/policy' => 'static_pages#policy'
    get '/contact' => 'static_pages#contact'
    get '/demotivators' => 'static_pages#demotivators'
    get '/real_fun' => 'static_pages#real_fun'
 

	match ':controller(/:action(/:id))', :via => :get


end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :set_student, only: [:show]
    before_action :set_result, only: [:show, :edit, :update, :destroy], except: [:parent_filter, :index]
    #include is inheritence to get the contents of the helper. 
    #This is to avoid writing repetative code and is therefore achieveing DRYness
    include UsersHelper  


    def lfilter
        ##fixed BUG fix the lfiter by email it is vital function
        #add if the current user email matches the pfilter email the show (maybe in views) fixed!!!
        #st = params[:lfilter] (this does not work with emails for some reason)
        st ="%#{params[:lfilter]}%"
        #now compare that filter name with student
        @students= Student.where("surname like (?) or email like (?)",st, st) #
        #display all the pfilters
        #@pfilters = Pfilter.all
    end
    
    def parent_result
        @results= Result.all
        #get the current URI once on this page
        @URI = request.original_url
        #split the URI to get everything after the = sign
        @URI = @URI.split('=').last
        #take the % sign out of the string
        @URI = @URI.tr('%', '')
        #get everything befor 40 and everything after 40
        @splitEmailF =  @URI.split("40").first
        @splitEmailL =  @URI.split("40").last
        # to add between first and last in order to reconstruct the email
        @at="@"  
        @st=@splitEmailF.to_s+@at.to_s+@splitEmailL.to_s
        #saving the reconstructed email into a variable
        st=@splitEmailF.to_s+@at.to_s+@splitEmailL.to_s
        #searching the DB to match all the results of a student with the unique email
        @results= Result.where("email like ? ",st)    
    end
    
   def parent_search
      @search_term = params[:q]
      #@the search term is what will be presented in q
      st ="%#{params[:q]}%"
      #seatchterm will be used to search in students table searchin for the first name here
      @students = Student.where("surname like (?) or email like (?)", st, st)
 
    #returning all the results in the DB for all the students
    #@results = Result.all
    
    #get the current URI once on this page
    @URI = request.original_url
    #split the URI to get everything after the = sign
    @URI = @URI.split('=').last
    #take the % sign out of the string
    @URI = @URI.tr('%', '')
    #get everything befor 40 and everything after 40
    @splitEmailF =  @URI.split("40").first
    @splitEmailL =  @URI.split("40").last
    # to add between first and last in order to reconstruct the email
    @at="@"  
    @st=@splitEmailF.to_s+@at.to_s+@splitEmailL.to_s
    #saving the reconstructed email into a variable
    st=@splitEmailF.to_s+@at.to_s+@splitEmailL.to_s
    #searching the DB to match all the results of a student with the unique email
    @results= Result.where("email like ? ",st)
   end


    def parent_filter
       #add if the current user email matches the pfilter email the show (maybe in views)
        st = params[:pfilter]
        #now compare that filter name with student
        @students= Student.where("school like (?) or surname like (?) or email like (?)",st,st, st) #
        #BUG cant categorise by email from student DB (works with other params)
        #:filter is column in the schema table filters
        #name = params[:filter]
        #surname = params[:filter]
        #now compare that filter name with student
         #@students= Student.where("name like (?)" name.
        #where("user_id is not in (?)",[user_ids])
        #@students= Student.where("surname like (?)",surname)
        
        #make it work
        #email = "arthur@hotmail.com"
        #@students=Student.where("email like (?)",email)
    
    end
    
    def parent_pfilter
        #BUG cant categorise by email from student DB (works with other params)
        #:filter is column in the schema table filters
        #name = params[:filter]
        surname = params[:filter]
        #now compare that filter name with student
         #@students= Student.where("name like (?)" name.
      #where("user_id is not in (?)",[user_ids])
        @students= Student.where("surname like (?)",surname)
        
        #make it work
        #email = "arthur@hotmail.com"
        #@students=Student.where("email like (?)",email)
    
    end
    
    def index
         @students = Student.all
         @parent_filters = ParentFilter.all
         #@pfilters=Pfilter.all
         
        ##Here we personalise filters so that each user will have their own unique filter
        #displaying currnet user
        #the @vars are now available in views
        
        #user to be accessable on all of the pages
        @user = current_user
        #user_email for search purposes
        #@user_email = current_user.email
        #display the pfilters with the current user
        @lfilters= Lfilter.where("email like ? ", @user_email)  
    end
    



 private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :day_of_birth, :month_of_birth, :year_of_birth, :school, :email, :comment)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:date_time, :classes, :teacher, :grade, :email, :comment)
    end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/views/parents/_parent_filters.html.erb
<h1>Parental Filters</h1>
<br>
<table class="filters">
<%= link_to 'Edit Available Parental Filters', parent_filters_path %>
  
  <% @parent_filters.each do |filter| %>
      <tr>
        <td>
          
          <div class="filters">
               
           
           <p><%= filter.filter %></p>
           
           <a href="/parent_filter/<%= filter.filter %>"><%= filter.filter %></a>
          </div>
        
        </td>
      </tr>
    <% end %>
</table>

app/views/parents/index.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    
    <!-- the same applies to the rest of the code. The elemets that I've already declare that are comming form the template are similar below-->
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />


    <title><%= yield(:title) %>Parent's Dashboard</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>


    <!-- Bootstrap core CSS the --> <!--the line below is taken from a template
    <link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">-->
    <% stylesheet_link_tag "bootstrap.min"%>
    <!-- Animation library for notifications   --><!--the line below is taken from a template
    <link href="assets/stylesheets/animate.min.css" rel="stylesheet">-->
    <% stylesheet_link_tag "animate.min"%>
    <!--  Light Bootstrap Table core CSS    --><!--the line below is taken from a template
    <link href="assets/stylesheets/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet">-->
    <% stylesheet_link_tag "light-bootstrap-dashboard"%>


 <!--     Fonts and icons     --><!--the line below is taken from a template-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!--the line below is taken from a template-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">
    <!--the line below is taken from a template
    <link href="assets/stylesheets/pe-icon-7-stroke.css" rel="stylesheet">-->
   <% stylesheet_link_tag "pe-icon-7-stroke"%>


    
    <link href="https://ajax.googleapis.com/ajax/libs/jquery/3.0.1/jquery.min.jsy">
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
</head>
<body>

   <%= render 'layouts/header' %>

   <!-------------------------------------------------------------------------------  Filters TABLE BEGIN------------------>   


   <div class="content purple-horizontal">
       <p id="notice"><%= notice %></p>
       
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Filter Table</h4>
                            <p class="category">This table contains all students whose surname(s) or email(s) are in the filter table</p><br>
                            <p><%= link_to 'Add a Student Filter', new_lfilter_path , class: "btn purple-button" %> </p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                    <th class="text-left">Name</th>
                                    <th class="text-left">Date of Birth</th>
                                    <th class="text-left">School</th>
                                    <th class="text-left">Email</th>
                                    <th class="text-left">Rsults</th>
                                    <th class="text-left">Comment</th>
                                </thead>
                                
                                <!--ROW 1 -->
                                <!-- check if the code below works. if deleting the table all works so the prob is in the tble / the prob is that for sure the lfilters themselves is more than 0-->
                                <%#if (@students.length == 0 || @lfilters.length == 0) || (@students.length == 0 || @lfilters.length != 0) %>

                                <%#here I am checking if 1. No students or filters are made = error 2. or there are filters but no students = error. note made elsif for the second so that erros can be more specific%>
                                <%if (@students.length == 0 || @lfilters.length == 0) || (@students.length == 0 && @lfilters.length != 0) %>
                                <div class="col-md-12">
                                    <div class="card card-plain">
                                        <div class="header">
                                         <h4 class="text-warning">There are no resutls for the student/s you are looking for by what you are filtering (the student or/and the filter does not exist yet). Add a filter first and if same message appears then add a student)</h4>
                                         
                                     </div>
                                 </div>
                             </div>
                             <% end %>
                             <tbody>
                                
                                 <tr>   
                                    <!--ADD IF NO PFILTERS to display no filters result-->
                                    <!--IF ONE STUDENT IS THE RESULT OF THE FILTER THEN MAYBE GO STRAIGN TO MARKS?-->
                                    
                                    <% @lfilters.each do |lfilter| %>
                                    <% @students.each do |student| %>
                                    <% if lfilter.lfilter.casecmp(student.surname) == 0 || lfilter.lfilter.casecmp(student.email) == 0  %>
                                    <tr>
                                        <td ><%= "#{student.name} "  %><%= student.surname  %></td>
                                        <td ><%= "#{student.day_of_birth} /" %>  
                                            <%= "#{student.month_of_birth} /"%>
                                            <%= student.year_of_birth %></td>
                                            <td > <%= student.school %></td>
                                            <td > <%= student.email %></td>
                                            <td><%= link_to("Results", {:controller => 'results', :action => 'parent_result', :id =>  student.email}) %></td>
                                            <td > <%= student.comment %></td>

                                            <% end %>

                                            <% end %>


                                        </tbody>


                                    </td>
                                </tr>
                                
                                <%end%>
                                
                                
                            </table>

                        </div>
                    </div>
                </div>    
                
                
                <!------------------------------------------------------------------------------- All Students TABLE BEGIN------------------>   




                
                
                <div class="col-md-12">
                   
                   <p>
                      <button class="btn purple-button btn-primary" type="button" data-toggle="collapse" data-target="#collapse" aria-expanded="collapse">
                        Filter Table
                    </button>
                </p>
                <div class="collapse" id="collapse" >
                  <div class="card card-body">
                      
                      
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Filter Table</h4>
                            <p class="category">This table contains filters - school,surname or email</p><br>
                            <p><%= link_to 'Add a Student Filter', new_lfilter_path, class: "btn purple-button"  %> </p>
                        </div>
                        <div class="content table-responsive table-full-width">
                            <table class="table table-hover table-striped">
                                <thead>
                                  <th>Surname/Email</th>
                                  <!--<th>User's Email(delete)</th>-->
                                  <th class="text-left">Edit/Delete</th>
                              </thead>
                              
                              <!--ROW 1 -->
                              <!-- check if the code below works. if deleting the table all works so the prob is in the tble / the prob is that for sure the lfilters themselves is more than 0-->
                              <!-- check for 0 filters -->
                              <% if @lfilters.length == 0 %>
                              <div class="col-md-12">
                                <div class="card card-plain">
                                    <div class="header">
                                        <h4 class="text-warning">There are no matches in this filter (add a filter first to see resutls if student exist in the database)</h4><br>
                                        
                                    </div>
                                </div>
                            </div>
                            <% end %>
                            <tbody>
                                
                             <tr>   
                                <!--ADD IF NO PFILTERS to display no filters result-->
                                <!--IF ONE STUDENT IS THE RESULT OF THE FILTER THEN MAYBE GO STRAIGN TO MARKS?-->
                                
                                <% @lfilters.each do |lfilter| %>
                                <tr>
                                    <td><%= lfilter.lfilter %></td>
                                    <!-- <td><%# lfilter.email %></td>-->
                                    <td><% if current_user %>
                                        <%# link_to 'Show', lfilter %> 
                                        <%= link_to 'Edit', edit_lfilter_path(lfilter) %> /
                                        <%= link_to 'Delete', lfilter, method: :delete, data: { confirm: 'Are you sure?' } %>
                                        <%else%>
                                        <%end%>
                                    </td>
                                </tr>
                                
                                
                                <% end %>
                                
                            </table>

                        </div>
                    </div>
                </div>
                
                <!-------------------------------------------------------------------------------  Filter TABLE END------------------>   


                
                
            </div>
        </div>
        <tbody class="table-hover">
            <tr>
            </tr>

        </tbody>    
        <!-------------------------------------------------------------------------------  All Students TABLE END------------------>       
        


    </div>
</div>
</div>







</div>
<%= render 'layouts/footer' %>
</div>


</body>

<%javascript_include_tag "jquery.3.2.1.min.js"%>
<!--the line below is taken from a template
<script src="assets/javascripts/bootstrap.min.js" type="text/javascript"></script>-->
<%javascript_include_tag "bootstrap.min.js"%>
<!--  Charts Plugin --> <!--the line below is taken from a template
<script src="assets/javascripts/chartist.min.js"></script>-->
<%javascript_include_tag "chartist.min.js"%>
<!--  Notifications Plugin    --> <!--the line below is taken from a template
<script src="assets/javascripts/bootstrap-notify.js"></script>-->
<%javascript_include_tag "bootstrap-notify.js"%>


<!-- Light Bootstrap Table Core javascript and methods for Demo purpose --> 
<!--the line below is taken from a template
<script src="assets/javascripts/light-bootstrap-dashboard.js?v=1.4.0"></script>-->
<%javascript_include_tag "light-bootstrap-dashboard.js"%>




</html>






<!--
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Table Style</title>
    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>

<p id="notice"><%# notice %></p>

<h1>students/index</h1>
<body>
-->



 <!-- </body>

app/views/parents/lfilter.html.erb
<h1>Personal Filter Parents (views/students/lfilter.html.erb)</h1>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Categories Filter Parents</title>
    <meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>


<br/>

<% if @students.length == 0 %>
<!--empty filter error-->
<div id="empty" >
    <h2>We are sorry, 
        <br><br>
        there are no students
        <br><br>
    in this filter</h2>  
</div>
<% end %>

<div class="table-title">
    <h3>Students Table</h3>
</div>
<table class="table-fill">
   
    <thead>
        <tr>
            <p>"filter results so that newest if first</p>
            <th class="text-left">Name</th>
            <th class="text-left">Date of Birth</th>
            <th class="text-left">School</th>
            <th class="text-left">Email</th>
            <th class="text-left">Comment</th>

        </tr>
    </thead>
    <tbody class="table-hover">
        <% @students.each do |student| %>
        <tr>                                      
            <td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
            <td class="text-left"><%= "#{student.day_of_birth} /" %>  
                <%= "#{student.month_of_birth} /"%>
                <%= student.year_of_birth %></td>
                <td class="text-left"> <%= student.school %></td>
                <td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'parent_result', :id =>  student.email}) %>
                </td>
                <td class="text-left"> <%= student.comment %></td>

                
                
            </tr>
            <tr>

            </tr>

        </tbody>

        <% end %>
    </table>
    

</body>

app/views/parents/parent_filter.html.erb
<h1>Categories Parent Filter</h1>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Categories Filter</title>
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>

<body>
    <%='the uri fom the method is' %> <%=@splitEmailF%><%=    @URIL%> <br>


<% if @students.length == 0 %>
<!--empty filter error--->
  <div id="empty" >
    <h2>We are sorry, 
    <br><br>
    there are no students
    <br><br>
    in this filter</h2>  
  </div>
<% end %>

<div class="table-title">
<h3>Students Table</h3>
</div>
<table class="table-fill">
 
<thead>
<tr>
     
<th class="text-left">Name</th>
<th class="text-left">Date of Birth</th>
<th class="text-left">School</th>
<th class="text-left">Email</th>
<th class="text-left">Comment</th>
<th class="text-left">Edit/Destroy/Add</th>
</tr>
</thead>
<tbody class="table-hover">
    <% @students.each do |student| %>
<tr>                                      
<td class="text-left"><%= link_to "#{student.name} ", student %><%= student.surname  %></td>
<td class="text-left"><%= "#{student.day_of_birth} /" %>  
            <%= "#{student.month_of_birth} /"%>
            <%= student.year_of_birth %></td>
<td class="text-left"> <%= student.school %></td>
<td class="text-left"> <%= student.email %><%= link_to("Results", {:controller => 'results', :action => 'index', :id =>  student.email}) %>
</td>
<td class="text-left"> <%= student.comment %></td>
<td class="text-left"> <% if user_signed_in? %>
              <%= link_to 'Edit', edit_student_path(student) %>
              <%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' } %>
               <%else%>
            <%end%> </td>
            
           
</tr>
<tr>

</tr>

</tbody>

 <% end %>
</table>
  

  </body>

app/views/parents/parent_results.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Results for Parents</h1>

<table>
  <thead>
    <tr>
      <th>Date time</th>
      <th>Classes</th>
      <th>Teacher</th>
      <th>Grade</th>
      <th>Email</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.date_time %></td>
        <td><%= result.classes %></td>
        <td><%= result.teacher %></td>
        <td><%= result.grade %></td>
        <td><%= result.email %><%= link_to("Results", {:controller => 'parents', :action => 'parent_result', :id =>  result.email}) %>
</td>
        <td><%= result.comment %></td>
     </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>