config/routes.rb
Rails.application.routes.draw do
    
    resources :students do 
        resources :results
    end
    
    resources :results
    resources :students
    resources :users
    resources :pfilters
    resources :lfilters
    resources :parents

    post '/search' => 'students#search'

    get 'sessions/new'

    get 'sessions/create'

    get 'sessions/destroy'


  
    resources :sessions, only: [:new, :create, :destroy]
    get 'signup', to: 'users#new', as: 'signup'
    get 'login', to: 'sessions#create', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'page/index'
    
    # You can have the root of your site routed with "root"
    #ROOT PAGE IS THE STATI_COTROLLER'S INDEX METHOD WHICH WILL BE RENDERED IN VIEWS
    root 'static_pages#home'
    get '/about' => 'static_pages#about'
    get '/policy' => 'static_pages#policy'
    get '/contact' => 'static_pages#contact'
    get '/demotivators' => 'static_pages#demotivators'
    get '/real_fun' => 'static_pages#real_fun'
 

	match ':controller(/:action(/:id))', :via => :get


end

app/views/layouts/_filters.html.erb
<h1>Filters</h1>
<br>
<table class="filters">
<%= link_to 'Edit Available Filters', filters_path %>
  
  <% @filters.each do |filter| %>
      <tr>
        <td>
          
          <div class="filters">
               
           
           <p><%= filter.filter %></p>
           
           <a href="/filter/<%= filter.filter %>"><%= filter.filter %></a>
          </div>
        
        </td>
      </tr>
    <% end %>
</table>

app/views/layouts/_footer.html.erb
<!--the line below is taken from a template-->
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
               
                <li>
                    <a href="/static_pages/about.html">
                     
                       <!-- <p>About Us</p> -->
                    </a>
                </li>
                
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <a href="" target="_blank">TopTenJokes</a>, humour extends your lifespan 
        </p>
    </div>
</footer>

app/views/layouts/_header.html.1.erb
<div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="assets/images/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="https://www.linkedin.com/in/vadim-malakhovski/" class="simple-text">
                    EJournal
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="parents.html">
                        <i class="pe-7s-graph"></i>
                        <p>Parents</p>
                    </a>
                </li>
                <li>
                    <a href="students.html">
                        <i class="pe-7s-user"></i>
                        <p>Teachers</p>
                    </a>
                </li>
                <li>
                    <a href="views/static_pages/table.html.erb">
                        <i class="pe-7s-note2"></i>
                        <p>Education Articles</p>
                    </a>
                </li>
                <li>
                    <a href="typography.html">
                        <i class="pe-7s-news-paper"></i>
                        <p>About Us</p>
                    </a>
                </li>
                  <!--
                <li>
                    <a href="icons.html">
                        <i class="pe-7s-science"></i>
                        <p>How To Tutorial</p>
                    </a>
                </li>
              
                <li>
                    <a href="maps.html">
                        <i class="pe-7s-map-marker"></i>
                        <p>Maps</p>
                    </a>
                </li>
                -->
                <li>
                    <a href="notifications.html">
                        <i class="pe-7s-bell"></i>
                        <p>Notifications</p>
                    </a>
                </li>
				<li class="active-pro">
                    <a href="upgrade.html">
                        <i class="pe-7s-rocket"></i>
                        <p>Support Us</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--<a class="navbar-brand" href="#">Dashboard</a>-->
<!-------------------------------------------------------------------------------  headers-->
                    <!--going back-->
                    <a class="navbar-brand" href="../">
                      <%= "Home"%>
                    <% link_to "Home", root_path  %>
                    </a>
 <!-------------------------------------------------------------------------------  END  headers-->                
                 
                     <a class="navbar-brand" href="#">
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
								<p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-lg hidden-md"></b>
									<p class="hidden-lg hidden-md">
										5 Notifications
										<b class="caret"></b>
									</p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>
                        <li>
                           <a href="">
                                <i class="fa fa-search"></i>
								<p class="hidden-lg hidden-md">Search</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                     
                     <!--USER name + surename ----------------------------------------------------------------------------------------->
                     <!--add if loged in user if not loged in login/signup-->
                     <li>
                     <a href="">
                      <p><%= "Welcome:   #{@user}" %></p>
                      </a>
                      </li>
                      <!--USER name + surename END----------------------------------------------------------------------------------------->
                      
                       <!-- delete on completion
                        <li>
                           <a href="">
                               <p>Account</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
										Dropdown
										<b class="caret"></b>
									</p>

                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                        </li>
                        <li>
                        -->
                         
                               <% if current_user %>
                       
                         <li>  
                            <a href="logout">
                 
                 <%= "Log Out"%>
                 <% link_to "Log Out", logout_path  %>
                 </a>
                </li> 
          <% else %> 
         
               <li>  
                 <li> 
                     <a  class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    <!--href="signup"-->
                 
                      <%="Register"%>
                      <%# link_to 'Register', signup_path %>
                      </a>
                      


                      <%# render 'form' %>

<%# link_to 'Back', users_path %>
                      </li> 
                      

      
         
                      <li> 
                      <a>or</a>
                      </li> 
                        
                          <li> 
                    <a href="login"> 
                  
                     <%="Sign In"%>
                     <%link_to 'Sign in', login_path %>
                     </a>

                      </li>   
                   </li>  
              

<div class="collapse" id="collapseExample">
  <div class="card card-body">
   <%= form_for User.new do |f| %>
  <% if User.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

   </div>
</div>


             <% end %>                   <!-- <p>Log out</p>             </li>-->
                           
                      
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>
<!-- add _name.html.erb and then can render in another vews html.erb file + can be rendered on multiple pages to maintain DRY principle
<div id='header'>
</div>
<div id='menu'>
    <div id='navbar'>
         <ul>
            <li><%# link_to "Home",   root_path %></li>
             <li><%# link_to "Post", posts_path %></li>
            <li><%# link_to "Help",   help_path %></li>
            <li><%# link_to "About",  about_path %></li>
            <li><%# link_to "Log in", admin_path %></li>
            <li><%# link_to "Signup", signup_path %></li>
            <li><%# link_to "Log in", login_path %></li>
            <li><%# link_to "Log Out", logout_path %></li>
            <li><%# link_to "___THIS IS FROM DEVISE___"%></li>
            
            <%# if current_user %>
                 <div>Signed in as... <%#current_user.email %> (<%#link_to 'Sign out', logout_path, :method => :delete %>)</div>
          <%#else %>
                 <%#link_to 'Register', signup_path %> or <%# link_to 'Sign in', login_path %>
          <%#end %>

         </ul>      
    </div>
</div>
-->


<!--

                      <script>
                      $(document).ready(function() {
 

                        $("form#login-box").bind "ajax:success", (e, data, status, xhr) ->
    if data.success
      //javascript that executes if everything goes o.k.
      $('#sign_in').modal('hide');
      $('#sign_in_button').hide();
      $('#submit_comment').slideToggle(1000, "easeOutBack" );
    else
      alert('failure!');
      $('#submit').click(function(){
    alert("hi");
 });
      });</script>
      
      
                          <li> 
                 <a href="login">  

                    <h2>Sign in</h2>  
                
   <%#devise_error_messages! %>
   <%#form_for(resource, :as => resource_name, :url => session_path(resource_name) ,:html => {:id => "login-box"},:format => :json, :remote => true ) do |f| %>

 
    <%# f.email_field :email, :class => "form-control", :placeholder => "Email", autocomplete: "on" %>
   <%# f.password_field :password, :class => "form-control", :placeholder => "Password", autocomplete: "off" %>

       <%# if devise_mapping.rememberable? -%>
       <%# f.check_box :remember_me, :style => "margin-top:20px;margin-bottom:20px;" %>
       <%# f.label :remember_me, :style => "margin-top:20px;margin-bottom:20px;" %>
       <%#end -%>


       <%# f.submit "Sign In", :class => "btn btn-default btn-login", :id=> "submit"%>

       <%# end %>
    </div>
    
   -->

app/views/layouts/_header.html.erb
<!--the line below is taken from a template-->
<div class="wrapper">
    <!--the line below is taken from a template-->
    <div class="sidebar" data-color="purple">


        <div class="sidebar-wrapper" >
            <div class="logo">
                <a href="" target="_blank" class="simple-text">
                    TopTenJokes
                </a>
            </div>

 <ul class="nav">
     
                 <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'home'}) do %>
                    <%= image_tag("icons/home32.png", :alt => "home", :class => "header_icons") %>
                    <span>Home</span>
                    <% end %>
                </li>
                
                <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'demotivators'}) do %>
                    <%= image_tag("icons/demotivators32.png", :alt => "demotivators", :class => "header_icons") %>
                    <span>Demotivators</span>
                    <% end %>
                </li>
                
                <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'real_fun'}) do %>
                    <%= image_tag("icons/real_fun32.png", :alt => "real_fun", :class => "header_icons") %>
                    <span>Really Funny</span>
                    <% end %>
                </li>

     
                <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'about'}) do %>
                    <%= image_tag("icons/teachers32.png", :alt => "about", :class => "header_icons") %>
                    <span>About Us</span>
                    <% end %>
                </li>
                
                <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'policy'}) do %>
                    <%= image_tag("icons/articles32.png", :alt => "policy", :class => "header_icons") %>
                    <span>Private Policy</span>
                    <% end %>
                </li>

                <li>
                    <%= link_to ({:controller => 'static_pages', :action => 'contact'}) do %>
                    <%= image_tag("icons/about32.png", :alt => "contact", :class => "header_icons") %>
                    <span>Contact Us</span>
                    <% end %>
                </li>

            
            </ul>
            
        </div>
    </div>
    <!--the line below is taken from a template-->
    <div class="main-panel ">
        <!--the line below is taken from a template but eddited classes-->
        <nav class="navbar navbar-default navbar-fixed ">
            <!--the line below is taken from a template-->
            <div class="container-fluid">
                <div class="navbar-header">
                    <!--the line below is taken from a template params eddited-->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <!--the line below is taken from a template and eddited-->
                        <span class="sr-only">Toggle navigation</span>
                        <!--the line below is taken from a template-->
                        <span class="icon-bar"></span>
                        <!--the line below is taken from a template-->
                        <span class="icon-bar"></span>
                        <!--the line below is taken from a template-->
                        <span class="icon-bar"></span>
                    </button>
                    <!--<a class="navbar-brand" href="#">Dashboard</a>-->
                    <!-- headers-->
                    <!--going back-->
                    <a class="navbar-brand" href="..">
                        <p class="font-weight-bold"><i class="fa fa-home"></i>  <%=" Home" %></p>


                    </a>
                </div>
                <!--END  headers-->   
                <!-- the same applies to the rest of the code. The elemets that I've already declare that are comming form the template are similar below-->



                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                       
                    </ul>



                </div>
            </div>
        </nav>

app/views/layouts/_lfilters.html.erb
<h1>Personal Filters Parents</h1>
<br>
<table class="filters">
<%= link_to 'Edit Available Personal Filters', lfilters_path %>
  
  <% @lfilters.each do |lfilter| %>
      <tr>
        <td>
          
          <div class="filters">
               
           
           <p><%= lfilter.lfilter %></p>
           
           <a href="/lfilter/<%= lfilter.lfilter %>"><%= lfilter.lfilter %></a>
          </div>
        
        </td>
      </tr>
    <% end %>
</table>

app/views/layouts/_pfilters.html.erb
<h1>Personal Filters</h1>
<br>
<table class="filters">
<%= link_to 'Edit Available Personal Filters', pfilters_path %>
  
  <% @pfilters.each do |pfilter| %>
      <tr>
        <td>
          
          <div class="filters">
               
           
           <p><%= pfilter.pfilter %></p>
           
           <a href="/pfilter/<%= pfilter.pfilter %>"><%= pfilter.pfilter %></a>
          </div>
        
        </td>
      </tr>
    <% end %>
</table>

app/views/layouts/_search.html.erb
<%= form_tag("/search" , :method => "post") do %>

<%# label_tag("Search by Surname, email or school:")  %>
<%= link_to image_tag("icons/search-purple48.gif",alt:"Search Icon",class:"purple", class:"icons", id:"search_icon", :size => '28x28') %>
<%= text_field_tag(:q, nil, placeholder: 'surname, email or school') %>
<%= submit_tag("Search",class:"purple") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!--adding Favicon to the tab-->    
  <%= favicon_link_tag 'favicon-196.png' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :defaults %>


<!-- Bootstrap core CSS the --> <!--the line below is taken from a template
<link href="assets/stylesheets/bootstrap.min.css" rel="stylesheet">-->
<% stylesheet_link_tag "bootstrap.min"%>
<!-- Animation library for notifications   --><!--the line below is taken from a template
<link href="assets/stylesheets/animate.min.css" rel="stylesheet">-->
<% stylesheet_link_tag "animate.min"%>
<!--  Light Bootstrap Table core CSS    --><!--the line below is taken from a template
<link href="assets/stylesheets/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet">-->
<% stylesheet_link_tag "light-bootstrap-dashboard"%>


<!--     Fonts and icons     --><!--the line below is taken from a template-->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<!--the line below is taken from a template-->
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700,300" rel="stylesheet" type="text/css">
<!--the line below is taken from a template
<link href="assets/stylesheets/pe-icon-7-stroke.css" rel="stylesheet">-->
<% stylesheet_link_tag "pe-icon-7-stroke"%>



<link href="https://ajax.googleapis.com/ajax/libs/jquery/3.0.1/jquery.min.js">
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->


</head>
<body>
  <!--!!!!!I could have added header  her so that they would be displayd on every page but my design is to prevent header on the results pages--> 



  <%= yield %>

</body>
<!--   Core JS Files   --> <!--the line below is taken from a template
<script src="assets/javascripts/jquery.3.2.1.min.js" type="text/javascript"></script>-->

<%javascript_include_tag "jquery.3.2.1.min.js"%>
<!--the line below is taken from a template
<script src="assets/javascripts/bootstrap.min.js" type="text/javascript"></script>-->
<%javascript_include_tag "bootstrap.min.js"%>
<!--  Charts Plugin --> <!--the line below is taken from a template
<script src="assets/javascripts/chartist.min.js"></script>-->
<%javascript_include_tag "chartist.min.js"%>
<!--  Notifications Plugin    --> <!--the line below is taken from a template
<script src="assets/javascripts/bootstrap-notify.js"></script>-->
<%javascript_include_tag "bootstrap-notify.js"%>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose --> 
<!--the line below is taken from a template
<script src="assets/javascripts/light-bootstrap-dashboard.js?v=1.4.0"></script>-->
<%javascript_include_tag "light-bootstrap-dashboard.js"%>
</html>